#define LARGO_FORMULARIO 1400
#define ALTO_FORMULARIO 700
#define DX_DESPLAZAMIENTO_LIANA 200

#define VELOCIDAD_LIANA_RAPIDO -0.10
#define VELOCIDAD_LIANA_MEDIO -0.08
#define VELOCIDAD_LIANA_LENTO -0.07
#define VELOCIDAD_LIANA_MUY_LENTO -0.06

#define TAMAÑO_LIANA_GRANDE 160
#define TAMAÑO_LIANA_MEDIO 150
#define TAMAÑO_LIANA_PEQUEÑO 140
#define TAMAÑO_LIANA_MUY_PEQUEÑO 130

#define LARGO_TARZAN 20
#define LARGO_TARZAN_NADANDO 40
#define ALTO_TARZAN 30
#define ALTO_TARZAN_NADANDO 20
#define LARGO_TARZAN_BATALLA 30
#define ALTO_TARZAN_BATALLA 20

#define LARGO_COCODRILO 30
#define ALTO_COCODRILO 20

#define LARGO_CUCHILLO 20
#define ALTO_CUCHILLO 20

#define LARGO_JANE 25
#define ALTO_JANE 50

#define LARGO_NATIVO 65
#define ALTO_NATIVO 120

#define LARGO_ANIMALES_SELVA 60
#define ALTO_ANIMALES_SELVA 15